# Header Menu
menu:
  Home: /
  Archive: /archives/ # can set archive-dir in root config to custom value
  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Miscellaneous
color_scheme: blue   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
default_author: Anonymous

about: 重点专项课题1
email: jyy@nju.edu.cn
address_1: Department of Computer Science and Technology
address_2: 163 Xianlin Avenue
address_3: Nanjing, China, 210023
