# Header Menu
menu:
  首页: /
  归档: /archives/ # can set archive-dir in root config to custom value
   
# Miscellaneous
color_scheme: blue   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
default_author: Growinware

about: 可持续演化的智能化软件理论、方法和技术<br><br>可成长的智能化网构软件范型理论、方法与技术研究
email: jyy@nju.edu.cn
address_1: 南京市栖霞区仙林大道163号
address_2: 南京大学仙林校区
address_3: 计算机科学与技术系
